theme: jekyll-theme-hacker
title: SamTheeSeagull's CTF Guides
description: A list of my write-ups of TryHackMe rooms.
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Write Ups
    url: setup
